package com.rizahanmiy.newsapp.utils.constants

object AppConstants {

    const val NEWS_PREF = "NEWS_PREF"
    const val PAYMENT_ID = "idPayment"
    const val PAYMENT_VALUE = "paymentValue"
    const val PAYMENT = "payment"
    const val REFRESH = "refresh"
    const val FROM = "from"
    const val METHOD = "method"
    const val DEEPLINK = "deeplink"
    const val URL = "url"
    const val HARVEST = "harvest"
    const val MODEL = "model"
    const val COUPON = "model"
    const val HISTORY = "history"

    const val LOGIN_REQUEST = "request"

    object KeyIntents{
        const val KEY_HARVEST_DATE = "harvestDate"
        const val KEY_PRODUCT = "product"
        const val KEY_PROFILE = "profile"
        const val KEY_PRODUCTS = "products"
        const val KEY_CONTENT_VIEW = "content_view"
        const val KEY_SEARCH = "searchKey"
        const val KEY_PAYMENT_VALUE = "paymentValue"
        const val KEY_MODEL = "model"
        const val KEY_REFERRAL_CODE = "codeReferral"
        const val KEY_ID_PRODUCT_FARMER = "idProductFarmer"
        const val KEY_BLOG = "blog"
        const val KEY_POSITION = "position"
        const val KEY_TITLE = "title"
        const val KEY_ADDRESS_ID = "idAddress"
        const val KEY_ADDRESS_PURPOSE = "purposeAddress"
        const val KEY_ADDRESS = "address"
        const val KEY_PAYMENT_METHODS = "paymentMethods"
        const val KEY_TOTAL_NETTO = "totalNetto"
        const val KEY_SPLIT_PAYMENT = "splitPayment"
        const val KEY_IS_CHANGE_PAYMENT = "isChangePayment"
        const val KEY_URL = "url"
        const val KEY_CHECKOUT = "checkout"
        const val KEY_PROMOTION = "promotion"
        const val KEY_PROMO_CODE = "promo_code"
        const val KEY_WARNING = "warning"
    }

    object KeyPreferences{
        const val KEY_ACCESS_TOKEN = "KEY_ACCESS_TOKEN"
        const val KEY_TOKEN_FIREBASE = "KEY_TOKEN_FIREBASE"
        const val KEY_IS_LOGIN = "KEY_IS_LOGIN"
        const val KEY_CART = "KEY_CART"
        const val KEY_EMAIL = "KEY_EMAIL_USER"
        const val KEY_NAME_USER = "KEY_NAME_USER"
        const val KEY_ID_USER = "KEY_ID_USER"
        const val KEY_NOTIF = "KEY_NOTIF"
        const val KEY_HARVEST_DATE = "KEY_HARVEST_DATE"
        const val KEY_SEARCH = "KEY_SEARCH"
        const val KEY_UNREAD = "KEY_UNREAD"
        const val KEY_REGISTERED = "KEY_REGISTERED"
        const val KEY_CART_NULL = "KEY_CART_NULL"
        const val KEY_ISCHECKOUT = "KEY_ISCHECKOUT"
        const val KEY_IS_ONBOARDING = "KEY_IS_ONBOARDING"
        const val KEY_IS_ONBOARDING_QUANTITY = "KEY_IS_ONBOARDING_QUANTITY"
        const val KEY_IS_ONBOARDING_SOCIAL_BUYING = "KEY_IS_ONBOARDING_SOCIAL_BUYING"
        const val KEY_IS_WELCOME_SOCIAL_BUYING = "KEY_IS_WELCOME_SOCIAL_BUYING"
        const val KEY_IS_COACH_MARK_SOCIAL_BUYING = "KEY_IS_COACH_MARK_SOCIAL_BUYING"
        const val KEY_IS_COACH_MARK_SOCIAL_BUYING_BUTTON = "KEY_IS_COACH_MARK_SOCIAL_BUYING_BUTTON"
        const val KEY_IS_COACH_MARK_CASHBACK_SOCIAL_BUYING = "KEY_IS_COACH_MARK_CASHBACK_SOCIAL_BUYING"
        const val KEY_IS_COACH_MARK_RATING_HOME = "KEY_IS_COACH_MARK_RATING_HOME"
        const val KEY_IS_COACH_MARK_RATING_DETAIL = "KEY_IS_COACH_MARK_RATING_DETAIL"
        const val KEY_IS_COACH_MARK_FIRST_COUPON = "KEY_IS_COACH_MARK_FIRST_COUPON"
        const val KEY_IS_COACH_MARK_INPUT_COUPON = "KEY_IS_COACH_MARK_INPUT_COUPON"
        const val KEY_IS_COACH_MARK_COUPON_DETAIL = "KEY_IS_COACH_MARK_COUPON_DETAIL"
    }

    object PaymentValueType{
        const val GOPAY = "GOPAY"
        const val SHOPEEPAY = "SHOPEEPAY"
        const val LINKAJA = "LINKAJA"
        const val CREDIT_CARD = "CCNP"
    }
}